### ISSUE TITLE
Acquire a gamepad

### ISSUE THREAD

**Issue by marian42** [Autonomous-Racing-PG/ros.package#80]
- [x] Decide which model of gamepad should be used (Xbox One, 360, Playstation, wired/wireless, bluetooth?)
- [x] Order the gamepad
- [ ] Get reimbursed (ask about this in advance)
