### ISSUE TITLE
Create style guide

### ISSUE THREAD

**Issue by marian42** [Autonomous-Racing-PG/ros.package#90]
- [x] Create a style guide based on the one for ROS ( http://wiki.ros.org/CppStyleGuide )
- [ ] Create a wiki article with the new style guide
- [x]  Make sure everyone agrees on it, if needed create polls
- [ ] Apply new style to our existing code
